/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "000148441.h"

#ifndef _CLIENTAUX
#define _CLIENTAUX
void *readFile(char *path, char *host, int *numvals, int *arr1len, int *arr2len)
{

    char buffer[1024];
    char values_raw[101];
    int num_elems;

    FILE *file = fopen(path, "r");

    if (file == NULL)
    {
        printf("Cannot open %s\n", path);
        exit(8);
    }
    fgets(buffer, 1024, file);
    if (sscanf(buffer, "%s %d %[^\t\n]", host, &num_elems, values_raw) != 3)
    {
        perror("El archivo tiene un formato incorrecto\n");
        exit(4);
    }

    fclose(file);
    int *valores = (int *)malloc(sizeof(int) * num_elems);
    *numvals = num_elems;
    char *token = strtok(values_raw, " ");

    for (int i = 0; token != NULL; i++)
    {
        valores[i] = atoi(token);
        token = strtok(NULL, " ");
    }

    *arr1len = num_elems / 2;
    *arr2len = *arr1len;

    return valores;
}

void *readArgs(int argc, char *argv[], int *arr1len, int *arr2len){

    //Número de argumentos a leer es siempre es argv[2]
    int num_elems = atoi(argv[2]);
    int *valores = (int *)malloc(sizeof(int) * num_elems);
    
    for(int i = 0 ; i < num_elems; i++){
        valores[i] = atoi(argv[3 + i]);
    }
    
    *arr1len = num_elems / 2;
    *arr2len = *arr1len;

    return valores;
}


void genArrays(int *values, int numValues, int* array1, int* array2, int array1len, int array2len){

    if(numValues % 2 == 1){
        //Es impar, ignorar elemento de la mitad
        for(int i = 0; i < array1len; i++){
           array1[i] = values[i];
           array2[i] = values[i + array1len + 1];
        }
    }
    else{
        for(int i = 0; i < array1len; i++){
           array1[i] = values[i];
           array2[i] = values[i + array1len];
        }
    }   
}

int mayorValor(int *arr, int size){
    int max = arr[0];
    for(int i = 0; i < size; i++){
        if(arr[i] > max){
            max = arr[i];
        }
    }

    return max;
}
#endif

void
prog_mahc_1(char *host)
{
        CLIENT *clnt;
        int  *result_1;
        arrays  productopunto_1_arg;
        double  *result_2;
        arrays  mediorangoespecial_1_arg;

#ifndef DEBUG
        clnt = clnt_create (host, PROG_MAHC, VERS_MAHC, "udp");
        if (clnt == NULL) {
                clnt_pcreateerror (host);
                exit (1);
        }
#endif  /* DEBUG */

        result_1 = productopunto_1(&productopunto_1_arg, clnt);
        if (result_1 == (int *) NULL) {
                clnt_perror (clnt, "call failed");
        }
        result_2 = mediorangoespecial_1(&mediorangoespecial_1_arg, clnt);
        if (result_2 == (double *) NULL) {
                clnt_perror (clnt, "call failed");
        }
#ifndef DEBUG
        clnt_destroy (clnt);
#endif   /* DEBUG */
}


int main(int argc, char *argv[])
{
    int *valores;
    int numVals;
    char host[20];
    int arr1len;
    int arr2len;

    CLIENT *clnt;
    int *result_1;
    arrays productopunto_1_arg;
    double *result_2;
    arrays mediorangoespecial_1_arg;

    if (argc == 2)
    {
        valores = (int *)readFile(argv[1], host, &numVals, &arr1len, &arr2len);
    }
    else if (argc > 2)
    {
        //host siempre es argv[1]
        strcpy(host, argv[1]);
        valores = (int *)readArgs(argc, argv, &arr1len, &arr2len);
        numVals = atoi(argv[2]);
    }
    else
    {
        printf("Cantidad de argumentos inválida\n");
        exit(1);
    }
    printf("Calling RPC on %s\n", host);

#ifndef DEBUG
        clnt = clnt_create (host, PROG_MAHC, VERS_MAHC, "udp");
        if (clnt == NULL) {
                clnt_pcreateerror (host);
                exit (1);
        }
#endif  /* DEBUG */

    //Generar estructura
    genArrays(valores, numVals, productopunto_1_arg.arr1, productopunto_1_arg.arr2, arr1len, arr2len);
    genArrays(valores, numVals, mediorangoespecial_1_arg.arr1, mediorangoespecial_1_arg.arr2, arr1len, arr2len);
    free(valores);

    productopunto_1_arg.arr1len = arr1len;
    productopunto_1_arg.arr2len = arr2len;
    mediorangoespecial_1_arg.arr1len = arr1len;
    mediorangoespecial_1_arg.arr2len = arr2len;

    int mayorVec1 = mayorValor(productopunto_1_arg.arr1, arr1len);
    int mayorVec2 = mayorValor(productopunto_1_arg.arr2, arr2len);

    if (mayorVec1 >= mayorVec2)
    {
        result_1 = productopunto_1(&productopunto_1_arg, clnt);
        if (result_1 == (int *)NULL)
        {
            clnt_perror(clnt, "call failed");
        }
        printf("Producto Punto: %d\n", *result_1);
    }
    else
    {
        result_2 = mediorangoespecial_1(&mediorangoespecial_1_arg, clnt);
        if (result_2 == (double *)NULL)
        {
            clnt_perror(clnt, "call failed");
        }
        printf("Medio Rango Especial: %f\n", *result_2);
    }

#ifndef DEBUG
        clnt_destroy (clnt);
#endif   /* DEBUG */

    exit(0);
}
