const char *FILE_SERVICE_PATH = "./file_service/";
const short MAX_FILENAME_SIZE = 31;


const short MAX_INSTRUCTION_SIZE = 33;
const short MAX_COMMAND_SIZE = 24;


const short MAX_STUDENT_NAME_ARG_SIZE = 124;
const short MAX_STUDENT_SEMESTER_ARG_SIZE = 3;
const short MAX_STUDENT_ID_ARG_SIZE = 3;
const short MAX_STUDENT_REGISTER_SIZE = 130; //MAX_STUDENT_NAME_ARG_SIZE + MAX_STUDENT_ID_ARG_SIZE + MAX_STUDENT_SEMESTER_ARG_SIZE

const short MAX_CONCURRENT_FILE_DB = 2;


const char CHAR_WHITELIST[] = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz1234567890 ";