/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "productoPunto.h"

int *
productopunto_1_svc(vectores *argp, struct svc_req *rqstp)
{
        static int  result;

        /*
         * insert server code here
         */

        return &result;
}

double *
mediorangoespecial_1_svc(vectores *argp, struct svc_req *rqstp)
{
        static double  result;

        /*
         * insert server code here
         */

        return &result;
}
